const configs={
    "API_BASE":"http://crashoverride.dlinkddns.com:2000",
    "STUDENT_WISE_LAB_REPORT":"/student-dashboard/labs/report",
    "GET_STUDENT_LAB":"/student-dashboard/get-my-labs",
    "COMPLETED_EXAMS":"/student-dashboard/exams/completed",
    "UPCOMING_EXAMS":"/student-dashboard/exams/upcoming",
    "EXAM_COMPLETED":"/student-dashboard/exams/completed",
    "EXAM_UPCOMING":"/student-dashboard/exams/upcoming",
    "GET_COURSES":"/student-dashboard/get-courses",
    "GET_LEADERBOARD":"/student-dashboard/courses/leaderboard",
    "ENABLE_EXAM_SESSION":"/student-dashboard/exams/enable-exam-session",
    "GET_EXAM_QUESTION":"/student-dashboard/exams/get-exam-questions",
    "SUBMIT_EXAMS":"/student-dashboard/exams/submit",
    "ENABLE_CONTEST_SESSION":"/student-dashboard/contests/enable-contest-session",
    "GET_CONTEST_CHALLENGES":"/student-dashboard/contests/get-contest-session-challenges",
    "SUBMIT_CONTEST":"/student-dashboard/contests/submit",
    "CONTEST_EXECUTE":"/student-dashboard/contests/execute",
    "CONTEST_LEADERBOARD":"/student-dashboard/contests/leaderboard",
    "ENABLE_LAB_SESSION":"/student-dashboard/labs/enable-lab-session",
    "GET_LAB_CONTENT":"/student-dashboard/labs/get-lab-content",
    "SUBMIT_LAB":"/student-dashboard/labs/submit",
    "GET_LAB_SUBMISSIONS":"/student-dashboard/get-lab-submissions",
    "LABS_EXECUTE":"/student-dashboard/labs/execute",
    "PRACTICE_GET_TAGS":"/student-dashboard/get-tags",
    "PRACTICE_GET_CHALLENGES":"/student-dashboard/practice/get-challenges",
    "PRACTICE_GET_CHALLENGE":"/student-dashboard/practice/get-challenge",
    "PRACTICE_EXECUTE":"/student-dashboard/practice/execute",
    "PRACTICE_SUBMIT":"/student-dashboard/practice/submit",
    "PRACTICE_GET_SUBMISSIONS":"/student-dashboard/practice/get-practice-submissions",
    "GET_PROFILE_DETAILS":"/student-dashboard/get-profile-details",
    "UPDATE_PROFILE_DETAILS":"/student-dashboard/update-profile-details",
    "NOTIFICATION_EMAIL_UPDATE":"/student-dashboard/send-notification-to-update-email",
    "UPDATE_EMAIL":"/student-dashboard/update-email",
    "END_CONTEST_SESSION":"/student-dashboard/contests/end-session",
    "END_LAB_SESSION":"/student-dashboard/labs/end-session",
    "DOWNLOAD_LAB_REPORT":"/student-dashboard/download-lab-code",
    "GET_UPCOMING_CONTESTS":"/student-dashboard/contests/upcoming",
    "GET_FINISHED_CONTESTS":"/student-dashboard/contests/completed",
    "GET_CONTEST_LEADERBOARD":"/student-dashboard/contests/completed-leaderboard"
}

export const getApiConfig = (suffix)=>{
    return configs["API_BASE"]+configs[suffix];
}