const configs = {
    "API_BASE": "http://crashoverride.dlinkddns.com:2000",
    "API_POST_LOGIN": "/login",
    "GET_USER_ROLE": "/get-user-role",
    "API_REGISTER": "/register",
    "FORGOT_PASSWORD": "/forget-password",
    "ENTITY_DETAILS": "/admin/entity-details",
    "NO_OF_ENTITIES": "/number-of-entities",
    "GET_ALL_COURSES": "/courses/get-all-courses",
    "GET_ALL_DEPARTMENTS": "/get-all-departments",
    "GET_ALL_YEARS": "/get-all-years",
    "ADD_USER": "/admin/new-user",
    "COURSE_FILTER": "/courses/filter",
    "GET_facultyS_ON_COURSEID": "/courses/get-allocated-facultys",
    "GET_ENTITIES_ON_COURSEID": "/courses/get-allocated-entities",
    "ALLOCATE_ENTITIES_COURSE": "/courses/allocation",
    "ALLOCATE_ENTITIES_LAB": "/labs/allocation ",
    "GET_ALL_LABS": "/get-all-labs",
    "GET_FACULTIES_ON_LABID": "/labs/get-allocated-faculties",
    "GET_ENTITIES_ON_LABID": "/labs/get-allocated-entities",
    "LABS_FILTER": "/labs/filter",
    "EXAMS_FILTER": "/exams/filter",
    "ALLOCATE_FACULTIES_EXAMS": "/admin/manage-exam/allocate-faculties",
    "MODIFY_faculty": "/admin/modify-faculty-details",
    "MODIFY_FACULTY": "/admin/modify-faculty-details",
    "TAG_SEARCH": "/admin/manage-exam/get-question",
    "ADD_QUESTION": "/admin/manage-exam/create-question",
    "CREATE_EXAM": "/admin/manage-exam/create-exam",
    "GET_ALL_EXAMS": "/admin/manage-exam/get-all-exams",
    "GET_EXAM_DETAILS": "/admin/manage-exam/get-exam",
    "GET_ALLOCATED_FACULTIES_FOR_EXAM": "/admin/manage-exam/get-allocated-faculties",
    "GET_QUESTIONS": "/admin/manage-exam/get-question-by-id",
    "UPDATE_QUESTION": "/admin/manage-exam/update-question",
    "EDIT_EXAM": "/admin/manage-exam/edit-exam",
    "NEW_CHALLENGE": "/challenges/new",
    "GET_TAGS": "/challenges/get-tags",
    "GET_CHALLENGE": "/challenges/get-challenge",
    "UPDATE_CHALLENGE": "/challenges/update",
    "CREATE_CONTEST": "/contests/create-contest",
    "GET_CONTEST": "/contests/get-contest",
    "UPDATE_CONTEST": "/contests/update-contest",
    "GET_LIST": "/contests/manage-status/",
    "GET_COURSE_CONTENT":"/faculty-dashboard/courses/get-course-content",
    "UNLOCK_LESSON":"/faculty-dashboard/courses/unlock-lesson",
    "GET_PRACTICE_CHALLENGES":"/faculty-dashboard/courses/get-practice-challenges",
    "GET_TEST_CHELLENGES":"/faculty-dashboard/courses/get-test-challenges",
    "UNLOCK_MODULE":"/faculty-dashboard/courses/unlock-module",
    "PRACTICE_SUBMIT":"/faculty-dashboard/courses/practice-submit",
    "TEST_SUBMIT":"/faculty-dashboard/courses/test-submit",
    "EXECUTE_CODE":"/faculty-dashboard/courses/execute",
    "GET_PRACTICE_SUBMISSIONS":"/faculty-dashboard/courses/get-practice-submissions",
    "GET_TEST_SUBMISSIONS":"/faculty-dashboard/courses/get-test-submissions",
    "GET_STUDENT_COURSE_CONTENT":"/student-dashboard/courses/get-course-content",
    "UNLOCK_STUDENT_LESSON":"/student-dashboard/courses/unlock-lesson",
    "GET_STUDENT_PRACTICE_CHALLENGES":"/student-dashboard/courses/get-practice-challenges",
    "GET_STUDENT_TEST_CHELLENGES":"/student-dashboard/courses/get-test-challenges",
    "UNLOCK_STUDENT_MODULE":"/student-dashboard/courses/unlock-module",
    "PRACTICE_STUDENT_SUBMIT":"/student-dashboard/courses/practice-submit",
    "TEST_STUDENT_SUBMIT":"/student-dashboard/courses/test-submit",
    "EXECUTE_STUDENT_CODE":"/student-dashboard/courses/execute",
    "GET_STUDENT_PRACTICE_SUBMISSIONS":"/student-dashboard/courses/get-practice-submissions",
    "GET_STUDENT_TEST_SUBMISSIONS":"/student-dashboard/courses/get-test-submissions",
    "ENABLE_EXAM_SESSION":"/student-dashboard/exams/enable-exam-session",
    "ENABLE_CONTEST_SESSION":"/student-dashboard/contests/enable-contest-session",
    "ENABLE_LAB_SESSION":"/student-dashboard/labs/enable-lab-session",
    "GET_ALL_NOTIFICATIONS":"/student-dashboard/get-all-notifications"
}

export const getApiConfig = (suffix) => {
    return configs["API_BASE"] + configs[suffix];
}

export const constants = {
    "TEST_TIME":180     
}